% ERPLAB history file generated on 05-Jul-2021
% ---------------------------------------------

EEG.etc.eeglabvers = '14.1.2'; % this tracks which version of EEGLAB is being used, you may ignore it



EEG= pop_creabasiceventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99 }, 'BoundaryString', { 'boundary' }, 'Eventlist', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\eventlist.txt' );% Script: 05-Jul-2021 18:04:47

EEG= pop_binlister( EEG , 'BDF', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\bin for winter.txt', 'IndexEL',1, 'SendEL2', 'EEG', 'Voutput', 'EEG' );% Script: 05-Jul-2021 18:04:48

EEG = pop_epochbin( EEG , [0.01100.0],[ 0.1 300]);% Script: 05-Jul-2021 18:04:50

EEG= pop_artextval( EEG , 'Channel',1:6, 'Flag',1, 'Threshold', [ -100 100], 'Twindow', [ 0.1 1099.1] );% Script: 05-Jul-2021 18:04:50
EEG= pop_basicfilter( EEG,1:6 , 'Boundary', 'boundary', 'Cutoff', [ 1 20], 'Design', 'butter', 'Filter', 'bandpass', 'Order',2 );% Script: 05-Jul-2021 18:04:51

ERP = pop_averager( ALLEEG , 'Criterion', 'good', 'DSindex',5, 'ExcludeBoundary', 'on', 'SEM', 'on' );% Script: 05-Jul-2021 18:04:51
ERP = pop_filterp( ERP,1:6 , 'Cutoff', [ 0.1 20], 'Design', 'butter', 'Filter', 'bandpass', 'Order',2 );% Script: 05-Jul-2021 18:04:52
ERP = pop_erplindetrend( ERP, 'all' );% Script: 05-Jul-2021 18:04:52
ERP = pop_scalplot( ERP,1,0 , 'Blc', 'pre', 'Colormap', 'jet', 'Electrodes', 'on', 'FontName', 'Courier New', 'FontSize',10, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'both', 'Maptype', '2D', 'Mapview', '+X', 'Plotrad',0.55, 'Value', 'insta' );% GUI: 05-Jul-2021 18:09:40
ERP = pop_scalplot( ERP,2,0 , 'Blc', 'pre', 'Colormap', 'jet', 'Electrodes', 'on', 'FontName', 'Courier New', 'FontSize',10, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'both', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta' );% GUI: 05-Jul-2021 18:11:06
ERP = pop_ploterps( ERP, [ 1 2],1:6 , 'AutoYlim', 'on', 'Axsize', [ 0.05 0.08], 'BinNum', 'on', 'Blc', 'pre', 'Box', [ 3 2], 'ChLabel', 'on', 'FontSizeChan',10, 'FontSizeLeg',12, 'FontSizeTicks',10, 'LegPos', 'bottom', 'Linespec', {'k-' , 'r-' }, 'LineWidth',1, 'Maximize', 'on', 'Position', [ 103.714 24.7222 106.857 31.8889], 'Style', 'Classic', 'Tag', 'ERP_figure', 'Transparency',0, 'xscale', [ 0.0 1097.0 0:200:800 ], 'YDir', 'normal' );% GUI: 05-Jul-2021 18:11:26
ERP = pop_scalplot( ERP,2,0 , 'Blc', 'pre', 'Colormap', 'jet', 'Electrodes', 'on', 'FontName', 'Courier New', 'FontSize',10, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta' );% GUI: 05-Jul-2021 18:12:44
ERP = pop_scalplot( ERP,2,0 , 'Blc', 'pre', 'Colormap', 'jet', 'Electrodes', 'on', 'FontName', 'Courier New', 'FontSize',10, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '2D', 'Mapview', '+X', 'Plotrad',0.55, 'Position', [ 2095 -47 768 714], 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta' );% GUI: 05-Jul-2021 18:14:44
ERP = pop_scalplot( ERP,2,300 , 'Blc', 'pre', 'Colormap', 'jet', 'Electrodes', 'on', 'FontName', 'Courier New', 'FontSize',10, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2095 -47 768 714], 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta' );% GUI: 05-Jul-2021 18:15:37
ERP = pop_scalplot( ERP,2, [ 0 600] , 'Animated', 'on', 'Blc', 'pre', 'Colormap', 'jet', 'Compression', 'none', 'Electrodes', 'on', 'Filename', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\erpvideo.gif', 'FontName', 'Courier New', 'FontSize',10, 'FPS',2, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2130 245 768 714], 'Quality',60, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta', 'VideoIntro', 'erplab' );% GUI: 05-Jul-2021 18:16:52
ERP = pop_scalplot( ERP,2,0:50:600 , 'Animated', 'on', 'Blc', 'pre', 'Colormap', 'jet', 'Compression', 'none', 'Electrodes', 'on', 'Filename', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\erpvideo.gif', 'FontName', 'Courier New', 'FontSize',10, 'FPS',20, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2130 245 768 714], 'Quality',60, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta', 'VideoIntro', 'erplab' );% GUI: 05-Jul-2021 18:19:02
ERP = pop_scalplot( ERP,2,0:10:600 , 'Animated', 'on', 'Blc', 'pre', 'Colormap', 'jet', 'Compression', 'none', 'Electrodes', 'on', 'Filename', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\erpvideo.gif', 'FontName', 'Courier New', 'FontSize',10, 'FPS',100, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2130 245 768 714], 'Quality',60, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta', 'VideoIntro', 'erplab' );% GUI: 05-Jul-2021 18:20:20
ERP = pop_scalplot( ERP,2,0:5:450 , 'Animated', 'on', 'Blc', 'pre', 'Colormap', 'jet', 'Compression', 'none', 'Electrodes', 'on', 'Filename', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\erpvideo.gif', 'FontName', 'Courier New', 'FontSize',10, 'FPS',100, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2130 245 768 714], 'Quality',60, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta', 'VideoIntro', 'erplab' );% GUI: 05-Jul-2021 18:21:41
ERP = pop_scalplot( ERP,2,0:5:450 , 'Animated', 'on', 'Blc', 'pre', 'Colormap', 'jet', 'Compression', 'none', 'Electrodes', 'on', 'Filename', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\winter scrip\erpvideo.gif', 'FontName', 'Courier New', 'FontSize',10, 'FPS',100, 'Legend', 'bn-la', 'Maplimit', 'maxmin', 'Mapstyle', 'map', 'Maptype', '3D', 'Mapview', 'front', 'Plotrad',0.55, 'Position', [ 2130 245 768 714], 'Quality',60, 'Splinefile', 'C:\Users\my\Documents\MATLAB\eeglab14_1_2b\sample_locs\emotiv epoc locs.ced', 'Value', 'insta', 'VideoIntro', 'erplab' );% GUI: 05-Jul-2021 21:14:20
